//****************************************************************************//
// Verilog models generated by SiliconSmart M-2017.03-2 build date: Apr 12, 2017 14:36:58. (SMSC-2) //
// Siliconsmart Path: /cad/synopsys/SiliconSmart/M-2017.03-2/linux64/bin/siliconsmart //
// Host Name: r6cad-tsmc40r.stanford.edu, User Name: akashl, PID: 29084       //
// Directory: /home/akashl/NEM-Relay-CAD/liberty                              //
//                                                                            //
// File generated on Fri Dec 04 03:44:40 PST 2020. (SMSC-3)                   //
//****************************************************************************//


`timescale 1ns/1ps

// udp_data_begin


primitive UDP_nems40tt_nem_ohmux_invd0_2i_8b_UDP_0( ZN, S0, S1, I0, I1 );
  output ZN;
  input S0, S1, I0, I1;
  table
  //S0, S1, I0, I1: ZN
    1  0  0  ?: 1;
    0  1  ?  0: 1;
    1  0  1  ?: 0;
    0  1  ?  1: 0;
    1  1  ?  ?: x;
    0  0  ?  ?: x;
  endtable
endprimitive


`celldefine
module nem_ohmux_invd0_2i_8b_func( S0, S1 );
input S0, S1;

	UDP_nems40tt_nem_ohmux_invd0_2i_8b_UDP_0( ZN, S0, S1, I0, I1 );

endmodule
`endcelldefine
// udp_data_end
