//****************************************************************************//
// Verilog models generated by SiliconSmart M-2017.03-2 build date: Apr 12, 2017 14:36:58. (SMSC-2) //
// Siliconsmart Path: /cad/synopsys/SiliconSmart/M-2017.03-2/linux64/bin/siliconsmart //
// Host Name: r6cad-tsmc40r.stanford.edu, User Name: akashl, PID: 29084       //
// Directory: /home/akashl/NEM-Relay-CAD/liberty                              //
//                                                                            //
// File generated on Fri Dec 04 03:44:40 PST 2020. (SMSC-3)                   //
//****************************************************************************//


`timescale 1ns/1ps



`celldefine
module nem_ohmux_invd0_2i_8b( S0, S1 );
input S0, S1;

   `ifdef FUNCTIONAL  //  functional //

	nem_ohmux_invd0_2i_8b_func nem_ohmux_invd0_2i_8b_behav_inst(.S0(S0),.S1(S1));
   `else

	nem_ohmux_invd0_2i_8b_func nem_ohmux_invd0_2i_8b_inst(.S0(S0),.S1(S1));

	// spec_gates_begin


	// spec_gates_end



   specify

	// specify_block_begin 

	// comb arc I0_0 --> ZN_0
	 (I0_0 => ZN_0) = (1.0,1.0);

	// comb arc I0_0 --> ZN_1
	 (I0_0 => ZN_1) = (1.0,1.0);

	// comb arc I0_0 --> ZN_2
	 (I0_0 => ZN_2) = (1.0,1.0);

	// comb arc I0_0 --> ZN_3
	 (I0_0 => ZN_3) = (1.0,1.0);

	// comb arc I0_0 --> ZN_4
	 (I0_0 => ZN_4) = (1.0,1.0);

	// comb arc I0_0 --> ZN_5
	 (I0_0 => ZN_5) = (1.0,1.0);

	// comb arc I0_0 --> ZN_6
	 (I0_0 => ZN_6) = (1.0,1.0);

	// comb arc I0_0 --> ZN_7
	 (I0_0 => ZN_7) = (1.0,1.0);

	// comb arc I0_1 --> ZN_0
	 (I0_1 => ZN_0) = (1.0,1.0);

	// comb arc I0_1 --> ZN_1
	 (I0_1 => ZN_1) = (1.0,1.0);

	// comb arc I0_1 --> ZN_2
	 (I0_1 => ZN_2) = (1.0,1.0);

	// comb arc I0_1 --> ZN_3
	 (I0_1 => ZN_3) = (1.0,1.0);

	// comb arc I0_1 --> ZN_4
	 (I0_1 => ZN_4) = (1.0,1.0);

	// comb arc I0_1 --> ZN_5
	 (I0_1 => ZN_5) = (1.0,1.0);

	// comb arc I0_1 --> ZN_6
	 (I0_1 => ZN_6) = (1.0,1.0);

	// comb arc I0_1 --> ZN_7
	 (I0_1 => ZN_7) = (1.0,1.0);

	// comb arc I0_2 --> ZN_0
	 (I0_2 => ZN_0) = (1.0,1.0);

	// comb arc I0_2 --> ZN_1
	 (I0_2 => ZN_1) = (1.0,1.0);

	// comb arc I0_2 --> ZN_2
	 (I0_2 => ZN_2) = (1.0,1.0);

	// comb arc I0_2 --> ZN_3
	 (I0_2 => ZN_3) = (1.0,1.0);

	// comb arc I0_2 --> ZN_4
	 (I0_2 => ZN_4) = (1.0,1.0);

	// comb arc I0_2 --> ZN_5
	 (I0_2 => ZN_5) = (1.0,1.0);

	// comb arc I0_2 --> ZN_6
	 (I0_2 => ZN_6) = (1.0,1.0);

	// comb arc I0_2 --> ZN_7
	 (I0_2 => ZN_7) = (1.0,1.0);

	// comb arc I0_3 --> ZN_0
	 (I0_3 => ZN_0) = (1.0,1.0);

	// comb arc I0_3 --> ZN_1
	 (I0_3 => ZN_1) = (1.0,1.0);

	// comb arc I0_3 --> ZN_2
	 (I0_3 => ZN_2) = (1.0,1.0);

	// comb arc I0_3 --> ZN_3
	 (I0_3 => ZN_3) = (1.0,1.0);

	// comb arc I0_3 --> ZN_4
	 (I0_3 => ZN_4) = (1.0,1.0);

	// comb arc I0_3 --> ZN_5
	 (I0_3 => ZN_5) = (1.0,1.0);

	// comb arc I0_3 --> ZN_6
	 (I0_3 => ZN_6) = (1.0,1.0);

	// comb arc I0_3 --> ZN_7
	 (I0_3 => ZN_7) = (1.0,1.0);

	// comb arc I0_4 --> ZN_0
	 (I0_4 => ZN_0) = (1.0,1.0);

	// comb arc I0_4 --> ZN_1
	 (I0_4 => ZN_1) = (1.0,1.0);

	// comb arc I0_4 --> ZN_2
	 (I0_4 => ZN_2) = (1.0,1.0);

	// comb arc I0_4 --> ZN_3
	 (I0_4 => ZN_3) = (1.0,1.0);

	// comb arc I0_4 --> ZN_4
	 (I0_4 => ZN_4) = (1.0,1.0);

	// comb arc I0_4 --> ZN_5
	 (I0_4 => ZN_5) = (1.0,1.0);

	// comb arc I0_4 --> ZN_6
	 (I0_4 => ZN_6) = (1.0,1.0);

	// comb arc I0_4 --> ZN_7
	 (I0_4 => ZN_7) = (1.0,1.0);

	// comb arc I0_5 --> ZN_0
	 (I0_5 => ZN_0) = (1.0,1.0);

	// comb arc I0_5 --> ZN_1
	 (I0_5 => ZN_1) = (1.0,1.0);

	// comb arc I0_5 --> ZN_2
	 (I0_5 => ZN_2) = (1.0,1.0);

	// comb arc I0_5 --> ZN_3
	 (I0_5 => ZN_3) = (1.0,1.0);

	// comb arc I0_5 --> ZN_4
	 (I0_5 => ZN_4) = (1.0,1.0);

	// comb arc I0_5 --> ZN_5
	 (I0_5 => ZN_5) = (1.0,1.0);

	// comb arc I0_5 --> ZN_6
	 (I0_5 => ZN_6) = (1.0,1.0);

	// comb arc I0_5 --> ZN_7
	 (I0_5 => ZN_7) = (1.0,1.0);

	// comb arc I0_6 --> ZN_0
	 (I0_6 => ZN_0) = (1.0,1.0);

	// comb arc I0_6 --> ZN_1
	 (I0_6 => ZN_1) = (1.0,1.0);

	// comb arc I0_6 --> ZN_2
	 (I0_6 => ZN_2) = (1.0,1.0);

	// comb arc I0_6 --> ZN_3
	 (I0_6 => ZN_3) = (1.0,1.0);

	// comb arc I0_6 --> ZN_4
	 (I0_6 => ZN_4) = (1.0,1.0);

	// comb arc I0_6 --> ZN_5
	 (I0_6 => ZN_5) = (1.0,1.0);

	// comb arc I0_6 --> ZN_6
	 (I0_6 => ZN_6) = (1.0,1.0);

	// comb arc I0_6 --> ZN_7
	 (I0_6 => ZN_7) = (1.0,1.0);

	// comb arc I0_7 --> ZN_0
	 (I0_7 => ZN_0) = (1.0,1.0);

	// comb arc I0_7 --> ZN_1
	 (I0_7 => ZN_1) = (1.0,1.0);

	// comb arc I0_7 --> ZN_2
	 (I0_7 => ZN_2) = (1.0,1.0);

	// comb arc I0_7 --> ZN_3
	 (I0_7 => ZN_3) = (1.0,1.0);

	// comb arc I0_7 --> ZN_4
	 (I0_7 => ZN_4) = (1.0,1.0);

	// comb arc I0_7 --> ZN_5
	 (I0_7 => ZN_5) = (1.0,1.0);

	// comb arc I0_7 --> ZN_6
	 (I0_7 => ZN_6) = (1.0,1.0);

	// comb arc I0_7 --> ZN_7
	 (I0_7 => ZN_7) = (1.0,1.0);

	// comb arc I1_0 --> ZN_0
	 (I1_0 => ZN_0) = (1.0,1.0);

	// comb arc I1_0 --> ZN_1
	 (I1_0 => ZN_1) = (1.0,1.0);

	// comb arc I1_0 --> ZN_2
	 (I1_0 => ZN_2) = (1.0,1.0);

	// comb arc I1_0 --> ZN_3
	 (I1_0 => ZN_3) = (1.0,1.0);

	// comb arc I1_0 --> ZN_4
	 (I1_0 => ZN_4) = (1.0,1.0);

	// comb arc I1_0 --> ZN_5
	 (I1_0 => ZN_5) = (1.0,1.0);

	// comb arc I1_0 --> ZN_6
	 (I1_0 => ZN_6) = (1.0,1.0);

	// comb arc I1_0 --> ZN_7
	 (I1_0 => ZN_7) = (1.0,1.0);

	// comb arc I1_1 --> ZN_0
	 (I1_1 => ZN_0) = (1.0,1.0);

	// comb arc I1_1 --> ZN_1
	 (I1_1 => ZN_1) = (1.0,1.0);

	// comb arc I1_1 --> ZN_2
	 (I1_1 => ZN_2) = (1.0,1.0);

	// comb arc I1_1 --> ZN_3
	 (I1_1 => ZN_3) = (1.0,1.0);

	// comb arc I1_1 --> ZN_4
	 (I1_1 => ZN_4) = (1.0,1.0);

	// comb arc I1_1 --> ZN_5
	 (I1_1 => ZN_5) = (1.0,1.0);

	// comb arc I1_1 --> ZN_6
	 (I1_1 => ZN_6) = (1.0,1.0);

	// comb arc I1_1 --> ZN_7
	 (I1_1 => ZN_7) = (1.0,1.0);

	// comb arc I1_2 --> ZN_0
	 (I1_2 => ZN_0) = (1.0,1.0);

	// comb arc I1_2 --> ZN_1
	 (I1_2 => ZN_1) = (1.0,1.0);

	// comb arc I1_2 --> ZN_2
	 (I1_2 => ZN_2) = (1.0,1.0);

	// comb arc I1_2 --> ZN_3
	 (I1_2 => ZN_3) = (1.0,1.0);

	// comb arc I1_2 --> ZN_4
	 (I1_2 => ZN_4) = (1.0,1.0);

	// comb arc I1_2 --> ZN_5
	 (I1_2 => ZN_5) = (1.0,1.0);

	// comb arc I1_2 --> ZN_6
	 (I1_2 => ZN_6) = (1.0,1.0);

	// comb arc I1_2 --> ZN_7
	 (I1_2 => ZN_7) = (1.0,1.0);

	// comb arc I1_3 --> ZN_0
	 (I1_3 => ZN_0) = (1.0,1.0);

	// comb arc I1_3 --> ZN_1
	 (I1_3 => ZN_1) = (1.0,1.0);

	// comb arc I1_3 --> ZN_2
	 (I1_3 => ZN_2) = (1.0,1.0);

	// comb arc I1_3 --> ZN_3
	 (I1_3 => ZN_3) = (1.0,1.0);

	// comb arc I1_3 --> ZN_4
	 (I1_3 => ZN_4) = (1.0,1.0);

	// comb arc I1_3 --> ZN_5
	 (I1_3 => ZN_5) = (1.0,1.0);

	// comb arc I1_3 --> ZN_6
	 (I1_3 => ZN_6) = (1.0,1.0);

	// comb arc I1_3 --> ZN_7
	 (I1_3 => ZN_7) = (1.0,1.0);

	// comb arc I1_4 --> ZN_0
	 (I1_4 => ZN_0) = (1.0,1.0);

	// comb arc I1_4 --> ZN_1
	 (I1_4 => ZN_1) = (1.0,1.0);

	// comb arc I1_4 --> ZN_2
	 (I1_4 => ZN_2) = (1.0,1.0);

	// comb arc I1_4 --> ZN_3
	 (I1_4 => ZN_3) = (1.0,1.0);

	// comb arc I1_4 --> ZN_4
	 (I1_4 => ZN_4) = (1.0,1.0);

	// comb arc I1_4 --> ZN_5
	 (I1_4 => ZN_5) = (1.0,1.0);

	// comb arc I1_4 --> ZN_6
	 (I1_4 => ZN_6) = (1.0,1.0);

	// comb arc I1_4 --> ZN_7
	 (I1_4 => ZN_7) = (1.0,1.0);

	// comb arc I1_5 --> ZN_0
	 (I1_5 => ZN_0) = (1.0,1.0);

	// comb arc I1_5 --> ZN_1
	 (I1_5 => ZN_1) = (1.0,1.0);

	// comb arc I1_5 --> ZN_2
	 (I1_5 => ZN_2) = (1.0,1.0);

	// comb arc I1_5 --> ZN_3
	 (I1_5 => ZN_3) = (1.0,1.0);

	// comb arc I1_5 --> ZN_4
	 (I1_5 => ZN_4) = (1.0,1.0);

	// comb arc I1_5 --> ZN_5
	 (I1_5 => ZN_5) = (1.0,1.0);

	// comb arc I1_5 --> ZN_6
	 (I1_5 => ZN_6) = (1.0,1.0);

	// comb arc I1_5 --> ZN_7
	 (I1_5 => ZN_7) = (1.0,1.0);

	// comb arc I1_6 --> ZN_0
	 (I1_6 => ZN_0) = (1.0,1.0);

	// comb arc I1_6 --> ZN_1
	 (I1_6 => ZN_1) = (1.0,1.0);

	// comb arc I1_6 --> ZN_2
	 (I1_6 => ZN_2) = (1.0,1.0);

	// comb arc I1_6 --> ZN_3
	 (I1_6 => ZN_3) = (1.0,1.0);

	// comb arc I1_6 --> ZN_4
	 (I1_6 => ZN_4) = (1.0,1.0);

	// comb arc I1_6 --> ZN_5
	 (I1_6 => ZN_5) = (1.0,1.0);

	// comb arc I1_6 --> ZN_6
	 (I1_6 => ZN_6) = (1.0,1.0);

	// comb arc I1_6 --> ZN_7
	 (I1_6 => ZN_7) = (1.0,1.0);

	// comb arc I1_7 --> ZN_0
	 (I1_7 => ZN_0) = (1.0,1.0);

	// comb arc I1_7 --> ZN_1
	 (I1_7 => ZN_1) = (1.0,1.0);

	// comb arc I1_7 --> ZN_2
	 (I1_7 => ZN_2) = (1.0,1.0);

	// comb arc I1_7 --> ZN_3
	 (I1_7 => ZN_3) = (1.0,1.0);

	// comb arc I1_7 --> ZN_4
	 (I1_7 => ZN_4) = (1.0,1.0);

	// comb arc I1_7 --> ZN_5
	 (I1_7 => ZN_5) = (1.0,1.0);

	// comb arc I1_7 --> ZN_6
	 (I1_7 => ZN_6) = (1.0,1.0);

	// comb arc I1_7 --> ZN_7
	 (I1_7 => ZN_7) = (1.0,1.0);

	ifnone
	// comb arc posedge S0 --> (ZN_0:S0)
	 (posedge S0 => (ZN_0:S0)) = (1.0,1.0);

	ifnone
	// comb arc negedge S0 --> (ZN_0:S0)
	 (negedge S0 => (ZN_0:S0)) = (1.0,1.0);

	ifnone
	// comb arc posedge S0 --> (ZN_1:S0)
	 (posedge S0 => (ZN_1:S0)) = (1.0,1.0);

	ifnone
	// comb arc negedge S0 --> (ZN_1:S0)
	 (negedge S0 => (ZN_1:S0)) = (1.0,1.0);

	ifnone
	// comb arc posedge S0 --> (ZN_2:S0)
	 (posedge S0 => (ZN_2:S0)) = (1.0,1.0);

	ifnone
	// comb arc negedge S0 --> (ZN_2:S0)
	 (negedge S0 => (ZN_2:S0)) = (1.0,1.0);

	ifnone
	// comb arc posedge S0 --> (ZN_3:S0)
	 (posedge S0 => (ZN_3:S0)) = (1.0,1.0);

	ifnone
	// comb arc negedge S0 --> (ZN_3:S0)
	 (negedge S0 => (ZN_3:S0)) = (1.0,1.0);

	ifnone
	// comb arc posedge S0 --> (ZN_4:S0)
	 (posedge S0 => (ZN_4:S0)) = (1.0,1.0);

	ifnone
	// comb arc negedge S0 --> (ZN_4:S0)
	 (negedge S0 => (ZN_4:S0)) = (1.0,1.0);

	ifnone
	// comb arc posedge S0 --> (ZN_5:S0)
	 (posedge S0 => (ZN_5:S0)) = (1.0,1.0);

	ifnone
	// comb arc negedge S0 --> (ZN_5:S0)
	 (negedge S0 => (ZN_5:S0)) = (1.0,1.0);

	ifnone
	// comb arc posedge S0 --> (ZN_6:S0)
	 (posedge S0 => (ZN_6:S0)) = (1.0,1.0);

	ifnone
	// comb arc negedge S0 --> (ZN_6:S0)
	 (negedge S0 => (ZN_6:S0)) = (1.0,1.0);

	ifnone
	// comb arc posedge S0 --> (ZN_7:S0)
	 (posedge S0 => (ZN_7:S0)) = (1.0,1.0);

	ifnone
	// comb arc negedge S0 --> (ZN_7:S0)
	 (negedge S0 => (ZN_7:S0)) = (1.0,1.0);

	ifnone
	// comb arc posedge S1 --> (ZN_0:S1)
	 (posedge S1 => (ZN_0:S1)) = (1.0,1.0);

	ifnone
	// comb arc negedge S1 --> (ZN_0:S1)
	 (negedge S1 => (ZN_0:S1)) = (1.0,1.0);

	ifnone
	// comb arc posedge S1 --> (ZN_1:S1)
	 (posedge S1 => (ZN_1:S1)) = (1.0,1.0);

	ifnone
	// comb arc negedge S1 --> (ZN_1:S1)
	 (negedge S1 => (ZN_1:S1)) = (1.0,1.0);

	ifnone
	// comb arc posedge S1 --> (ZN_2:S1)
	 (posedge S1 => (ZN_2:S1)) = (1.0,1.0);

	ifnone
	// comb arc negedge S1 --> (ZN_2:S1)
	 (negedge S1 => (ZN_2:S1)) = (1.0,1.0);

	ifnone
	// comb arc posedge S1 --> (ZN_3:S1)
	 (posedge S1 => (ZN_3:S1)) = (1.0,1.0);

	ifnone
	// comb arc negedge S1 --> (ZN_3:S1)
	 (negedge S1 => (ZN_3:S1)) = (1.0,1.0);

	ifnone
	// comb arc posedge S1 --> (ZN_4:S1)
	 (posedge S1 => (ZN_4:S1)) = (1.0,1.0);

	ifnone
	// comb arc negedge S1 --> (ZN_4:S1)
	 (negedge S1 => (ZN_4:S1)) = (1.0,1.0);

	ifnone
	// comb arc posedge S1 --> (ZN_5:S1)
	 (posedge S1 => (ZN_5:S1)) = (1.0,1.0);

	ifnone
	// comb arc negedge S1 --> (ZN_5:S1)
	 (negedge S1 => (ZN_5:S1)) = (1.0,1.0);

	ifnone
	// comb arc posedge S1 --> (ZN_6:S1)
	 (posedge S1 => (ZN_6:S1)) = (1.0,1.0);

	ifnone
	// comb arc negedge S1 --> (ZN_6:S1)
	 (negedge S1 => (ZN_6:S1)) = (1.0,1.0);

	ifnone
	// comb arc posedge S1 --> (ZN_7:S1)
	 (posedge S1 => (ZN_7:S1)) = (1.0,1.0);

	ifnone
	// comb arc negedge S1 --> (ZN_7:S1)
	 (negedge S1 => (ZN_7:S1)) = (1.0,1.0);

	// specify_block_end 

   endspecify

   `endif 

endmodule
`endcelldefine
