##############################################################################
# Template generated by SiliconSmart M-2017.03-2 (built on Apr 12, 2017 14:36:58) #
# SiliconSmart Path: /cad/synopsys/SiliconSmart/M-2017.03-2/linux64/bin/siliconsmart #
# Host Name: r6cad-tsmc40r.stanford.edu, User Name: akashl, PID: 28057 #
# Directory: /home/akashl/NEM-Relay-CAD/liberty #
# Date Fri, 30 Oct 2020 20:59:10 PDT #
#                                                                            #
# Copyright (C) 2017 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower doCcs }

## 
## Formal Ports
$tempTestColl makeFormalPorts {
    I3_0
    I4_0
    S0
    I7_0
    S3
    S2
    S1
    I5_0
    S7
    S6
    I0_0
    S4
    S8
    S9
    S5
    I8_0
    I1_0
    I2_0
    ZN_0
    I6_0
    I9_0}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test leakage_power
set tempTest [ SBTest "leakage_power" ]
$tempTest setTargets { leakage_power }
$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1
$tempTest setStateCoverage "1"

## 
## ACQ_1
set tempAcq [ SBLeakageCurrentAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "!S0&!I0_0&!S1&!I1_0&!S2&!I2_0&!S3&!I3_0&!S4&!I4_0&!S5&!I5_0&!S6&!I6_0&!S7&!I7_0&!S8&!I8_0&S9&!I9_0&ZN_0"
$tempAcq setStateCoverage "1"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { I3_0 I4_0 I5_0 I7_0 S3 ZN_0:out S1 S0 S7 S6 S5 S4 S8 I1_0 I0_0 I8_0 S2 I2_0 I9_0 I6_0 S9 } { initial_delay units ct default_slew trailing_delay pp }

$tempWT setStimulus                       {   I3_0 I4_0 I5_0 I7_0 S3   S1   S0   S7   S6   S5   S4   S8   I1_0 I0_0 I8_0 S2   I2_0 I9_0 I6_0 S9   ZN_0  } {
                            "0"   { in0 } {   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    1     }
   "(0)+initial_delay+(1.0*pp)" { start } {   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    1     }
"(0)+initial_delay+(1.0*pp)+pp"   { end } {   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    1     }
}

$tempWT addMeasurements {} {
  { leakage_current      leakage_power { (0)+initial_delay+(1.0*pp) (0)+initial_delay+(1.0*pp)+pp {I0_0 I1_0 I2_0 I3_0 I4_0 I5_0 I6_0 I7_0 I8_0 I9_0 S0 S1 S2 S3 S4 S5 S6 S7 S8 S9} {} } NO_USER SYS }
}

$tempWT bindInterface { I3_0 I4_0 I5_0 I7_0 S3 ZN_0 S1 S0 S7 S6 S5 S4 S8 I1_0 I0_0 I8_0 S2 I2_0 I9_0 I6_0 S9 } { cell_initial_delay None[cycle_time] None[cycle_time] None[default_slew] cell_trailing_delay cell_power_period }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_ZN_0
$tempTopOp setOperation insert
$tempTopOp setNodes {ZN_0 ZN_0[logic_low_name]}
$tempTopOp setParam {load_ZN_0}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

