##############################################################################
# Template generated by SiliconSmart M-2017.03-2 (built on Apr 12, 2017 14:36:58) #
# SiliconSmart Path: /cad/synopsys/SiliconSmart/M-2017.03-2/linux64/bin/siliconsmart #
# Host Name: r6cad-tsmc40r.stanford.edu, User Name: akashl, PID: 888 #
# Directory: /home/akashl/NEM-Relay-CAD/liberty #
# Date Mon, 02 Nov 2020 14:28:46 PST #
#                                                                            #
# Copyright (C) 2017 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower doCcs }

## 
## Formal Ports
$tempTestColl makeFormalPorts {ZN S0 I1 I0 I3 I2 S3 S2 S1}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test delay__I1__lh__ZN__hl
set tempTest [ SBTest "delay__I1__lh__ZN__hl" ]
$tempTest setTargets { delay__I1__lh__ZN__hl Cin__I1__lh Tout__ZN__hl cap_energy__ZN__hl ccs_cin1__I1__lh ccs_cin2__I1__lh ccs_tin1__I1__lh ccs_tin2__I1__lh delay_ccs_native_current__I1__lh__ZN__hl energy1__I1__lh__ZN__hl__VB energy1__I1__lh__ZN__hl__VDD energy1__I1__lh__ZN__hl__VSS energy__I1__lh__ZN__hl leakage_power1__VB leakage_power1__VDD leakage_power1__VSS leakage_power2__VB leakage_power2__VDD leakage_power2__VSS time_at_voltage__I1__lh }
$tempTest setTargetInputs {
  {I1 lh}}

$tempTest setTargetOutputs {
  {ZN hl}}

$tempTest setSwitchingInputs {
  {I1 lh}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1
$tempTest setStateCoverage "1"

## 
## ACQ_1
set tempAcq [ SBDelayAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "S1&!I0&!I2&!I3&!S0&!S2&!S3"
$tempAcq setStateCoverage "1"
$tempAcq setAdditionalStateCoverage "1" "energy1__I1__lh__ZN__hl__VDD"
$tempAcq setAdditionalStateCoverage "1" "leakage_power1__VB"
$tempAcq setAdditionalStateCoverage "1" "leakage_power2__VSS"
$tempAcq setAdditionalStateCoverage "1" "energy__I1__lh__ZN__hl"
$tempAcq setAdditionalStateCoverage "1" "cap_energy__ZN__hl"
$tempAcq setAdditionalStateCoverage "1" "energy1__I1__lh__ZN__hl__VSS"
$tempAcq setAdditionalStateCoverage "1" "leakage_power1__VSS"
$tempAcq setAdditionalStateCoverage "1" "leakage_power1__VDD"
$tempAcq setAdditionalStateCoverage "1" "leakage_power2__VB"
$tempAcq setAdditionalStateCoverage "1" "leakage_power2__VDD"
$tempAcq setAdditionalStateCoverage "1" "energy1__I1__lh__ZN__hl__VB"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { ZN:inout I2 I1 I0 I3 S0 S3 S2 S1 } { initial_delay units ct default_slew pp prop_delay_level ccsPoints volt_tolerance stable energy_change_threshold energy_change_abs_threshold }

$tempWT setStimulus                                                {   I2   I1   I0   I3   S0   S3   S2   S1   ZN    } {
                                                 "0"            {} {   0    0    0    0    0    0    0    1    Z,1   }
                                     "initial_delay" { start out } {   -    1    -    -    -    -    -    -    Z,0   }
"max((initial_delay)+(pp),(initial_delay)+(stable))"            {} {   -    -    -    -    -    -    -    -    -,-   }
}

$tempWT addMeasurements {} {
  { tin_I1               Tin        { I1 start } NO_USER SYS }
  { cin_I1               Cin        { I1 start } NO_USER SYS }
  { ccs_cin1_I1          ccs_cin1   { I1 start } NO_USER SYS }
  { ccs_cin2_I1          ccs_cin2   { I1 start } NO_USER SYS }
  { ccs_tin1_I1          ccs_tin1   { I1 start } NO_USER SYS }
  { ccs_tin2_I1          ccs_tin2   { I1 start } NO_USER SYS }
  { ccs_time_ref_I1      time_at_voltage { I1 prop_delay_level*(__param_VDD-__param_VSS)+__param_VSS start } NO_USER SYS }
  { tout_ZN              Tout       { ZN out } NO_USER SYS }
  { delay_I1_ZN          delay      { I1 start ZN out } NO_USER SYS }
  { delay_ccs_native_current__I1__lh__ZN__hl delay_ccs_native_current { I1 start ZN VSS out (initial_delay)+(stable) load_ZN __param_VDD __param_VSS ccsPoints volt_tolerance } NO_USER SYS }
  { energy__I1__lh__ZN__hl energy     { start pp energy_change_threshold energy_change_abs_threshold 0 } NO_USER SYS }
  { energy1__I1__lh__ZN__hl__VDD energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 VDD } }
  { leakage_power1__VDD  leakage_power1 { initial_delay+0.95*pp initial_delay+pp VDD } }
  { leakage_power2__VDD  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp VDD } }
  { energy1__I1__lh__ZN__hl__VB energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 VB } }
  { leakage_power1__VB   leakage_power1 { initial_delay+0.95*pp initial_delay+pp VB } }
  { leakage_power2__VB   leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp VB } }
  { energy1__I1__lh__ZN__hl__VSS energy1    { start pp energy_change_threshold energy_change_abs_threshold 0 VSS } }
  { leakage_power1__VSS  leakage_power1 { initial_delay+0.95*pp initial_delay+pp VSS } }
  { leakage_power2__VSS  leakage_power2 { initial_delay+0.90*pp initial_delay+0.95*pp VSS } }
  { cap_energy__ZN__hl   cap_energy { start pp cap_ZN ZN 0 } }
}

$tempWT bindInterface { ZN I2 I1 I0 I3 S0 S3 S2 S1 } { cell_initial_delay I1[cycle_time] I1[cycle_time] I1[default_slew] cell_power_period I1[prop_delay_inp_level_rise] ZN[num_ccs_samples] ZN[ccs_max_voltage_error] ZN[stable_time] power_stabilization_threshold power_stabilization_threshold_absolute }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement dcvs
$tempTopOp setElementName cap_ground_ZN
$tempTopOp setOperation insert
$tempTopOp setNodes {ground_ZN 0}
$tempTopOp setParam {0}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_ZN
$tempTopOp setOperation insert
$tempTopOp setNodes {ZN ground_ZN}
$tempTopOp setParam {load_ZN}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

